# Generated by Django 5.0 on 2024-02-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='image',
            field=models.ImageField(default='book/images/gift-box.png', upload_to='book/images/'),
        ),
    ]
