# Generated by Django 5.0 on 2024-02-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0002_gift_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.ImageField(default='gift/media/images/gift-box.png', upload_to='gift/media/images/'),
        ),
    ]
