# Generated by Django 5.0 on 2024-02-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
