# Generated by Django 5.0 on 2024-02-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='user/media/images/default.png', upload_to='user/media/images/'),
        ),
    ]
